### ISSUE TITLE
org.apache.commons.lang3 package missing?

### ISSUE THREAD

**Issue by valioDOTch** [triplecheck/reporter#15]
When I started the jar (via bash) I got an error that the class "org.apache.commons.lang3.StringUtils" was missing. I fixed it by downloading the Commons Lang package, putting the classes in the corresponding subfolder (org/apache/commons) and repacking the jar.

I haven't looked in detail into the code yet.

**Comment by nunobrito** [comment]
Hi Valio, thanks for the feedback.

Typically I upload the packages for end-users on a different repository than this one. Could you point me to the jar file where you got the error so that I can replicate this issue?

Thank you.

**Comment by valioDOTch** [comment]
Hi nunobrito
The jar (repectively ".exe") stems from http://www.triplecheck.de/?ddownload=953 that was linked here http://www.triplecheck.de/download/

(sorry for the delay, missed the update)

**Comment by nunobrito** [comment]
Ok, thanks. This should be a glitch in the matrix. I'll get it sorted and then report back to this topic once I have more information.

**Comment by valioDOTch** [comment]
Any updates about this? ;-)

**Comment by nunobrito** [comment]
Sorry, none to report. Right now I'm rewriting part of the code that creates SPDX documents. The result is much faster but still not ready for a new public release. Don't have an estimation when this might occur, I'm aiming for next week to finish testing and ensure this defect doesn't happen.

Would you like to test a preview to ensure things work as expected?

**Comment by valioDOTch** [comment]
Yes, I would be willing to test a preview :)

**Comment by nunobrito** [comment]
Ok, this really helps..

I've uploaded a release candidate to the download folder at https://github.com/triplecheck/download/blob/master/triplecheck-1.0.0-RC.zip

Would you let me know if this issue got solved?

General feedback and opinion is welcome. Thank you. :-)

**Comment by valioDOTch** [comment]
With OpenJDK 7 (IcedTea 2.5.4) the error shows up again as soon as I try to start the "Create SPDX"  process.

Here's my std.err dump

    HK61 - Running hook /home/pat/Desktop/triplecheck/plugins/basic/ToolsLog.java HK61 - Running hook /home/pat/Desktop/triplecheck/plugins/webserver/server.java HK61 - Running hook 
    /home/pat/Desktop/triplecheck/plugins/components/showComponents.java HK61 - Running hook /home/pat/Desktop/triplecheck/plugins/licenses/search.java HK61 - Running hook 
    /home/pat/Desktop/triplecheck/plugins/spdx/create.java SU857 - Empty content on editor pane HK61 - Running hook /home/pat/Desktop/triplecheck/plugins/basic/home.java HK61 - Running 
    hook /home/pat/Desktop/triplecheck/plugins/spdx/showFileDetails.java HK61 - Running hook /home/pat/Desktop/triplecheck/plugins/spdx/showFileDetails.java HK61 - Running hook 
    /home/pat/Desktop/triplecheck/plugins/spdx/showFileDetails.java Exception in thread "Thread-11" bsh.TargetError: Method Invocation spdx.create : at Line: 183 : in file: inline 
    evaluation of: ``/* * SPDXVersion: SPDX-1.1 * Creator: Person: Nuno Brito (nuno.brito@tripleche . . . '' : spdx .create ( sourceCodeFolder ) Called from method: run : at Line: -1 : 
    in file: <Called from Java Code> : <Compiled Java Code> Target exception: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
    	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:97)
    	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
    	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47)
    	at bsh.BSHBlock.evalBlock(BSHBlock.java:130)
    	at bsh.BSHBlock.eval(BSHBlock.java:80)
    	at bsh.BshMethod.invokeImpl(BshMethod.java:362)
    	at bsh.BshMethod.invoke(BshMethod.java:258)
    	at bsh.BshMethod.invoke(BshMethod.java:186)
    	at bsh.This.invokeMethod(This.java:352)
    	at launchNewSPDX$38.run(BeanShell Generated via ASM (www.objectweb.org)) Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
    	at utils.hashing.similarity.levenshteinPercentage(similarity.java:34)
    	at license.LicenseInfer.processLicenseWithCache(LicenseInfer.java:151)
    	at license.LicenseInfer.processLicense(LicenseInfer.java:120)
    	at license.LicenseInfer.processFolder(LicenseInfer.java:104)
    	at license.LicenseInfer.<init>(LicenseInfer.java:69)
    	at spdxlib.DocumentCreate.launchCreateHeaderThread(DocumentCreate.java:497)
    	at spdxlib.DocumentCreate.createHeader(DocumentCreate.java:472)
    	at spdxlib.DocumentCreate.create(DocumentCreate.java:137)
    	at spdxlib.DocumentCreate.create(DocumentCreate.java:99)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at bsh.Reflect.invokeMethod(Reflect.java:146)
    	at bsh.Reflect.invokeObjectMethod(Reflect.java:79)
    	at bsh.Name.invokeMethod(Name.java:858)
    	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:75)
    	... 9 more Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    	... 26 more

**Comment by nunobrito** [comment]
Ok, thank you.

Still seems to be the Apache commons library causing an issue. I'll debug.

**Comment by valioDOTch** [comment]
Thanks a lot :) +1:

**Comment by justinmclean** [comment]
Also running into the same issue

**Comment by nunobrito** [comment]
Hi Justin, should be fixed now.

Can you test it again  please?

Download link: http://triplecheck.net/download/triplecheck.zip

Many thanks!
